CREATE TABLE NOTIFICATION
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOTIFIER BIGINT NOT NULL,
    NOTIFIER_NAME VARCHAR(100) NOT NULL,
    RECEIVER BIGINT NOT NULL,
    OUTER_ID BIGINT NOT NULL,
    OUTER_TITLE VARCHAR(256) NOT NULL,
    TYPE INT NOT NULL,
    GMT_CREATE BIGINT NOT NULL,
    STATUS INT DEFAULT 0 NOT NULL
);